/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ParentGuidRouteImport } from './routes/parent.$guid'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminMeetingsRouteImport } from './routes/admin.meetings'
import { Route as AdminInvitesRouteImport } from './routes/admin.invites'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminDinnerNotesRouteImport } from './routes/admin.dinner-notes'
import { Route as AdminBuyoutsRouteImport } from './routes/admin.buyouts'
import { Route as AdminBanquetRouteImport } from './routes/admin.banquet'
import { Route as ParentGuidIndexRouteImport } from './routes/parent.$guid.index'
import { Route as ParentGuidIdeasRouteImport } from './routes/parent.$guid.ideas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ParentGuidRoute = ParentGuidRouteImport.update({
  id: '/parent/$guid',
  path: '/parent/$guid',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMeetingsRoute = AdminMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDinnerNotesRoute = AdminDinnerNotesRouteImport.update({
  id: '/dinner-notes',
  path: '/dinner-notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuyoutsRoute = AdminBuyoutsRouteImport.update({
  id: '/buyouts',
  path: '/buyouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBanquetRoute = AdminBanquetRouteImport.update({
  id: '/banquet',
  path: '/banquet',
  getParentRoute: () => AdminRoute,
} as any)
const ParentGuidIndexRoute = ParentGuidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentGuidRoute,
} as any)
const ParentGuidIdeasRoute = ParentGuidIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => ParentGuidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/banquet': typeof AdminBanquetRoute
  '/admin/buyouts': typeof AdminBuyoutsRoute
  '/admin/dinner-notes': typeof AdminDinnerNotesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/parent/$guid': typeof ParentGuidRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/parent/$guid/ideas': typeof ParentGuidIdeasRoute
  '/parent/$guid/': typeof ParentGuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/banquet': typeof AdminBanquetRoute
  '/admin/buyouts': typeof AdminBuyoutsRoute
  '/admin/dinner-notes': typeof AdminDinnerNotesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/parent/$guid/ideas': typeof ParentGuidIdeasRoute
  '/parent/$guid': typeof ParentGuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/banquet': typeof AdminBanquetRoute
  '/admin/buyouts': typeof AdminBuyoutsRoute
  '/admin/dinner-notes': typeof AdminDinnerNotesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/parent/$guid': typeof ParentGuidRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/parent/$guid/ideas': typeof ParentGuidIdeasRoute
  '/parent/$guid/': typeof ParentGuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/banquet'
    | '/admin/buyouts'
    | '/admin/dinner-notes'
    | '/admin/emails'
    | '/admin/invites'
    | '/admin/meetings'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/students'
    | '/parent/$guid'
    | '/admin/'
    | '/parent/$guid/ideas'
    | '/parent/$guid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/banquet'
    | '/admin/buyouts'
    | '/admin/dinner-notes'
    | '/admin/emails'
    | '/admin/invites'
    | '/admin/meetings'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/students'
    | '/admin'
    | '/parent/$guid/ideas'
    | '/parent/$guid'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/banquet'
    | '/admin/buyouts'
    | '/admin/dinner-notes'
    | '/admin/emails'
    | '/admin/invites'
    | '/admin/meetings'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/students'
    | '/parent/$guid'
    | '/admin/'
    | '/parent/$guid/ideas'
    | '/parent/$guid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ParentGuidRoute: typeof ParentGuidRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/parent/$guid': {
      id: '/parent/$guid'
      path: '/parent/$guid'
      fullPath: '/parent/$guid'
      preLoaderRoute: typeof ParentGuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meetings': {
      id: '/admin/meetings'
      path: '/meetings'
      fullPath: '/admin/meetings'
      preLoaderRoute: typeof AdminMeetingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dinner-notes': {
      id: '/admin/dinner-notes'
      path: '/dinner-notes'
      fullPath: '/admin/dinner-notes'
      preLoaderRoute: typeof AdminDinnerNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buyouts': {
      id: '/admin/buyouts'
      path: '/buyouts'
      fullPath: '/admin/buyouts'
      preLoaderRoute: typeof AdminBuyoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banquet': {
      id: '/admin/banquet'
      path: '/banquet'
      fullPath: '/admin/banquet'
      preLoaderRoute: typeof AdminBanquetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/parent/$guid/': {
      id: '/parent/$guid/'
      path: '/'
      fullPath: '/parent/$guid/'
      preLoaderRoute: typeof ParentGuidIndexRouteImport
      parentRoute: typeof ParentGuidRoute
    }
    '/parent/$guid/ideas': {
      id: '/parent/$guid/ideas'
      path: '/ideas'
      fullPath: '/parent/$guid/ideas'
      preLoaderRoute: typeof ParentGuidIdeasRouteImport
      parentRoute: typeof ParentGuidRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBanquetRoute: typeof AdminBanquetRoute
  AdminBuyoutsRoute: typeof AdminBuyoutsRoute
  AdminDinnerNotesRoute: typeof AdminDinnerNotesRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminMeetingsRoute: typeof AdminMeetingsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBanquetRoute: AdminBanquetRoute,
  AdminBuyoutsRoute: AdminBuyoutsRoute,
  AdminDinnerNotesRoute: AdminDinnerNotesRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminMeetingsRoute: AdminMeetingsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParentGuidRouteChildren {
  ParentGuidIdeasRoute: typeof ParentGuidIdeasRoute
  ParentGuidIndexRoute: typeof ParentGuidIndexRoute
}

const ParentGuidRouteChildren: ParentGuidRouteChildren = {
  ParentGuidIdeasRoute: ParentGuidIdeasRoute,
  ParentGuidIndexRoute: ParentGuidIndexRoute,
}

const ParentGuidRouteWithChildren = ParentGuidRoute._addFileChildren(
  ParentGuidRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ParentGuidRoute: ParentGuidRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
